name: Auto Commit

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Make a change
        run: |
          echo "Last updated: $(date)" > log.txt

      - name: Commit and push
        run: |
          git config user.name "krlaskidata"
          git config user.email "${{ secrets.USER_EMAIL }}"
          
          git add log.txt
          git commit -m "chore: good morning commit"
          git push
